### ISSUE TITLE
Use setSecret instead of add-mask.

### ISSUE THREAD

**Issue by damccorm** [Azure/appservice-actions#3]
When setSecret is implemented on the actions toolkit, we should update to use that instead of add-mask (like we do in this PR https://github.com/Azure/appservice-actions/pull/2)

**Comment by N-Usha** [comment]
Thanks for reaching out @damccorm . We would like to inform that actions in this repo are now moved to new Git repos: https://github.com/Azure/webapps-deploy and https://github.com/Azure/webapps-container-deploy, Please update your workflows to use the new actions: azure/webapps-deploy@v1 and azure/webapps-container-deploy@v1 respectively.

**Comment by damccorm** [comment]
@bryanmacfarlane in case you want to follow up on this at all.
