### ISSUE TITLE
Error using `webapp-container` regarding creds/publish-profile

### ISSUE THREAD

**Issue by bitoiu** [Azure/appservice-actions#5]
Hey folks :wave:

I've previously used the `webapp` action successfully but decided to move towards containers with the `webapp-container` action. Using the example provided and the previous experience with the app services and also the `webapp` action I got stuck with the following error:

```
Run azure/appservice-actions/webapp-container@master
  with:
    app-name: qa-bookstore
    images: docker.pkg.github.com/ORG/REPO/bookstore:da2b518f8b2a513bcbc752b218fc06173e784d88
    publish-profile: ***
##[set-env name=AZURE_HTTP_USER_AGENT;]GITHUBACTIONS_DeployWebAppToAzure_d16a2d9642f325ed937e2887826407526199006da5fac7a9404a42d832b5f7a1
(node:2673) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getApplicationURL' of undefined
    at /home/runner/work/_actions/azure/appservice-actions/master/webapp-container/lib/main.js:60:68
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/azure/appservice-actions/master/webapp-container/lib/main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/azure/appservice-actions/master/webapp-container/lib/main.js:4:12)
    at main (/home/runner/work/_actions/azure/appservice-actions/master/webapp-container/lib/main.js:34:12)
    at Object.<anonymous> (/home/runner/work/_actions/azure/appservice-actions/master/webapp-container/lib/main.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
##[error]Error: No crdentails found. Please provide Publish Profile path or add a azure login script before this action or put credentiasl file in /home/auth.json.
(node:2673) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2673) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##[error]Node run failed with exit code 1
```

I'm puzzled with the error: `No crdentails found. Please provide Publish Profile path or add a azure login script before this action or put credentiasl file`. The `webapp` action does require a `publish-profile` and I've added one on my `yaml`, but checking the source, there's no input named `publish-profile` for this action. My currently `yaml` reads as follows (assume ✅ azure-login):

```
steps: 
    - name: Deploy Container to Azure    
      uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: 'qa-bookstore'
        images: 'docker.pkg.github.com/ORG/REPO/bookstore:${{ github.sha }}'
```

Adding the `publish-profile` doesn't help and I think as it stands it's not even an option.

Thanks in advance :blush:

:octocat::heart:

**Comment by bitoiu** [comment]
Hello @SumiranAgg :wave::bow: is this something you would be able to provide advice on?

:octocat::heart:

**Comment by bitoiu** [comment]
The only thing I've realized since I've opened the issue is that I'm using `azure-login` and not `docker-login` for authentication. To me it would continue to still use `azure-login` since I'm using containers within App Service. The imagine is built locally and I'm just trying to push the container, so that's why I didn't see the need to use the `docker-login`.

:octocat::heart:

**Comment by N-Usha** [comment]
Thanks @bitoiu for reaching out to us. We would like to inform you that the actions in this repo are now moved to new Git repos: https://github.com/Azure/webapps-deploy and https://github.com/Azure/webapps-container-deploy, Please update your workflows to use the new actions: azure/webapps-deploy@v1 and azure/webapps-container-deploy@v1 respectively
